version: "3.8"

services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_USER: $DB_USER
            MYSQL_PASSWORD: $DB_PASS
            MYSQL_ROOT_PASSWORD: $DB_PASS
            MYSQL_DATABASE: $DB_NAME
        ports:
            - "${DB_PORT:-13306}:3306"
